trigger: none 

parameters:
- name: modules
  displayName: Modules to add
  type: object
  default:
  - 'windows-virtual-machine'
  - 'linux-virtual-machine'
  - 'storage-account'
  - 'mssql'
  - 'app-service-environment'
  - 'app-service-plan'
  - 'app-service-windows'
  - 'app-service-linux'
  - 'vmss-windows'
  - 'vmss-linux'
  - 'linux-cluster'
  - 'windows-cluster'
  - 'container-group'
  - 'container-registry'
  - 'load-balancer'
  - 'front-door'
  - 'data-lake'
  - 'search-service'
  - 'application-insights'

- name: Environments
  displayName: Environment
  type: string
  # values: 
  # - 'prod'
  # - 'dev'
  # - 'sandbox'

steps:
- checkout: self
  persistCredentials: true
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
      set -e
      cd $ENV
      ./module_init.sh $MODULES

      git add .
      git commit -m "test push"
      git push origin HEAD:$(Build.SourceBranchName)
  env:
    ENV: ${{ parameters.Environments }}
